create the index.html styles.css and images files
soesandarwin2201/Portfolio_website pull request #1
Opened 2022-09-22 13:10 UTC by soesandarwin2201

//portfolio setup
//create linters to the project
//create index.html
//create styles.css
//create images file
//and commit it

2022-09-22 17:15 UTC, karlavdelgadof requested changes
# STATUS: INVALID CODE REVIEW :x: :stop_sign:  

Hi there @soesandarwin2201  :wave: , 

While you made a great effort in this project :100: , unfortunately, I cannot proceed to review your code. 

## Invalid Code Review Request :warning:

You have submitted a project, that has linter errors, kindly run the Stylelint linter on your local terminal and quickly fix them so you can get a review! :eyes:

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Make it work and then make it better!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-23 10:50 UTC, roshan-bajgain requested changes
Hi @soesandarwin2201, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Required Changes ♻️
- [ ] I would suggest you, please write the descriptive README file. Please use this [Template](https://github.com/microverseinc/readme-template/blob/master/README.md) but customize it
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 10:50 UTC, roshan-bajgain commented on index.html
> +
- [ ] I would suggest you please use `hx` tag for the sub-title for better semantic HTML

2022-09-23 10:50 UTC, roshan-bajgain commented on index.html
> +        <i class="uil uil-bars"></i>
- [ ] I would suggest you please use the same color and font defined in the template.
### Your design
![hisssssss](https://user-images.githubusercontent.com/81727988/191942430-70abc9d6-3b65-4ee6-9d68-6bcda43c1765.png)
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/191942462-78ec141f-068d-496e-80cb-82299742d602.png)

2022-09-23 10:50 UTC, roshan-bajgain commented on index.html
> +
- [ ] I would suggest you please the same color and the same font defined in the template. Please use `color: #344563` and `font-family: 'Poppins';`

2022-09-23 10:50 UTC, roshan-bajgain commented on index.html
> +      </ul>
- [ ] I would suggest you please use the same social media icons. You can use it by downloading it one by one from Figma and let's use the same font and same color for the `let's connect` subtitle.
### Your design
![his](https://user-images.githubusercontent.com/81727988/191944043-9cf0cc86-4ad8-4986-ba34-189dbea1cdf5.png)
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/191944086-5ab759da-dc38-422e-9e2f-39978fc7b26e.png)

2022-09-23 10:50 UTC, roshan-bajgain commented on index.html
> +  </div>
- [ ] I would suggest you please remove the commented code as it make the code unclean

2022-09-24 16:55 UTC, merged